/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package carreraciclistica.aplicacionconmenus;

/**
 *
 * @author Isaac
 */
public class VentanaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form VentanaPrincipal
     */
    public VentanaPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jMenuBar3 = new javax.swing.JMenuBar();
        jMenu7 = new javax.swing.JMenu();
        jMenu8 = new javax.swing.JMenu();
        jMenuBar4 = new javax.swing.JMenuBar();
        jMenu9 = new javax.swing.JMenu();
        jMenu10 = new javax.swing.JMenu();
        jPopupMenu1 = new javax.swing.JPopupMenu();
        EscritorioMorao = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        mnuSalir = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        mnuCalcularHipotenusa = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        mnuCalcularVoltaje = new javax.swing.JMenuItem();
        mnuCalcularCorriente = new javax.swing.JMenuItem();
        jMenu6 = new javax.swing.JMenu();
        mnuAcercade = new javax.swing.JMenuItem();

        jMenu3.setText("File");
        jMenuBar2.add(jMenu3);

        jMenu4.setText("Edit");
        jMenuBar2.add(jMenu4);

        jMenuItem1.setText("jMenuItem1");

        jMenu7.setText("File");
        jMenuBar3.add(jMenu7);

        jMenu8.setText("Edit");
        jMenuBar3.add(jMenu8);

        jMenu9.setText("File");
        jMenuBar4.add(jMenu9);

        jMenu10.setText("Edit");
        jMenuBar4.add(jMenu10);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Aplicacion Universidad Nacional de Colombia");

        EscritorioMorao.setBackground(new java.awt.Color(153, 0, 153));

        javax.swing.GroupLayout EscritorioMoraoLayout = new javax.swing.GroupLayout(EscritorioMorao);
        EscritorioMorao.setLayout(EscritorioMoraoLayout);
        EscritorioMoraoLayout.setHorizontalGroup(
            EscritorioMoraoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        EscritorioMoraoLayout.setVerticalGroup(
            EscritorioMoraoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 277, Short.MAX_VALUE)
        );

        jMenu1.setText("Archivo");

        mnuSalir.setText("Salir");
        mnuSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuSalirActionPerformed(evt);
            }
        });
        jMenu1.add(mnuSalir);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Pitagoras");

        mnuCalcularHipotenusa.setText("Calcular hipotenusa");
        mnuCalcularHipotenusa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuCalcularHipotenusaActionPerformed(evt);
            }
        });
        jMenu2.add(mnuCalcularHipotenusa);

        jMenuBar1.add(jMenu2);

        jMenu5.setText("Ohm");

        mnuCalcularVoltaje.setText("Calcular Voltaje");
        mnuCalcularVoltaje.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuCalcularVoltajeActionPerformed(evt);
            }
        });
        jMenu5.add(mnuCalcularVoltaje);

        mnuCalcularCorriente.setText("Calcular Corriente");
        mnuCalcularCorriente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuCalcularCorrienteActionPerformed(evt);
            }
        });
        jMenu5.add(mnuCalcularCorriente);

        jMenuBar1.add(jMenu5);

        jMenu6.setText("Acerca de");

        mnuAcercade.setText("Ver acerca de");
        mnuAcercade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuAcercadeActionPerformed(evt);
            }
        });
        jMenu6.add(mnuAcercade);

        jMenuBar1.add(jMenu6);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(EscritorioMorao)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(EscritorioMorao)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnuCalcularHipotenusaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuCalcularHipotenusaActionPerformed
        // TODO add your handling code here:
        frmCalcularHipotenusa pitagoras = new frmCalcularHipotenusa();
        EscritorioMorao.add(pitagoras);
        pitagoras.setClosable(true);
        pitagoras.setVisible(true);
        
    }//GEN-LAST:event_mnuCalcularHipotenusaActionPerformed

    private void mnuSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuSalirActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_mnuSalirActionPerformed

    private void mnuCalcularVoltajeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuCalcularVoltajeActionPerformed
        // TODO add your handling code here:
        frmCalcularVoltaje voltaje = new frmCalcularVoltaje();
        EscritorioMorao.add(voltaje);
        voltaje.setClosable(true);
        voltaje.setVisible(true);
    }//GEN-LAST:event_mnuCalcularVoltajeActionPerformed

    private void mnuAcercadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuAcercadeActionPerformed
        // TODO add your handling code here:
        frmVerAcercade acercade = new frmVerAcercade();
        EscritorioMorao.add(acercade);
        acercade.setClosable(true);
        acercade.setVisible(true);
    }//GEN-LAST:event_mnuAcercadeActionPerformed

    private void mnuCalcularCorrienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuCalcularCorrienteActionPerformed
        // TODO add your handling code here:
        frmCalcularCorriente corriente = new frmCalcularCorriente();
        EscritorioMorao.add(corriente);
        corriente.setClosable(true);
        corriente.setVisible(true);
    }//GEN-LAST:event_mnuCalcularCorrienteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane EscritorioMorao;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu10;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenu jMenu8;
    private javax.swing.JMenu jMenu9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuBar jMenuBar3;
    private javax.swing.JMenuBar jMenuBar4;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JMenuItem mnuAcercade;
    private javax.swing.JMenuItem mnuCalcularCorriente;
    private javax.swing.JMenuItem mnuCalcularHipotenusa;
    private javax.swing.JMenuItem mnuCalcularVoltaje;
    private javax.swing.JMenuItem mnuSalir;
    // End of variables declaration//GEN-END:variables
}
